### ISSUE TITLE
About shape/texture latent codes

### ISSUE THREAD

**Issue by Heathcliff-saku** [wbjang/code-nerf#4]
Hi，
  I am very interested in your work. After reading the article, I have a question: What method does CodeNeRF use to encode shape/texture, I think this part of the description in the article seems not clear enough

Looking forward to your answer!

**Comment by wbjang** [comment]
Hello, 

I think I do not understand your question clearly - I assume you asked about how I encode shape and texture to get disentanglement. 

NeRF models 1) the differential probability for shape(sigma), which only depends on XYZ 2) RGB for each point depending upon XYZ and viewpoint. Shape and texture do not have to be correlated - A car can have a red colour or green colour. Also, the colour of the ray depends on the viewing direction; the colour of a specific point does not contribute to the ray's colour when it is occluded - and this idea is beautifully captured in the volume rendering formula. CodeNeRF extends the above NeRF's idea by adding two latent vectors to generalize NeRF over multiple scenes. 

Cheers,
Wonbong

**Comment by Heathcliff-saku** [comment]
@wbjang 

Thank you for your answer, Sir. I get it, and I think I should read it again carefully

Look forward to your next update on the Editing Shapes/Textures code section, it's an exciting work!
